version: '3.7'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: "client"
    environment:
      NODE_ENV: 'development'
    volumes:
      - './client/:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    networks:
      front-net:
        aliases:
          - client

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: "server"
    ports:
      - "8080:8080"
    networks:
      front-net:
        aliases:
          - server
      back-net:
        aliases:
          - server
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
#    volumes:
#      - db-data:/var/lib/postgresql/data
    networks:
      back-net:
        aliases:
          - database

networks:
  front-net:
  back-net:

#volumes:
#  db-data: